### ISSUE TITLE
Analise do HTML feito em sala de aula.

### ISSUE THREAD

**Issue by MOVelasco** [Aline-fas/ProjettoWEB#1]
Olá Aline.

Estou olhando o GitHub do pessoal da turma. Conferindo oque produzimos em sala de aula ontem, o nosso primeiro documento HTML.
Estou estranhando que você esta só com um repositório, esta faltando o repositório feitoEmSalaDeAula, e esta faltando também o nosso primeiro documento feito em sala de aula.
Teve dificuldade para subir o arquivo?
Esta com alguma duvida no Git e/ou GitHub?
Me da um retorno.

**Comment by Aline-fas** [comment]
Obrigada por me sinalizar. Realmente não tinha subido o arquivo. Acabei de fazer as alterações!
